---
name: Validate Dockerfile for Dependabot use

on:
  push:
    paths:
      - '**/Dockerfile.yaml'
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - name: Mobydick Validation
      uses: jace-ys/mobydick-action@v0.1.0